version: "3.8"

services:
  api:
    build: .
    container_name: facefinder_api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/app

  client:
    build: ./client
    container_name: facefinder_client
    ports:
      - "8080:80"
    depends_on:
      - api

  redis:
    image: redis:latest
    container_name: facefinder_redis
    ports:
      - "6379:6379"
